sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: MiGheD4G+GECpbV0YyVo5H5cAXdfZ9YfDflLt04ghUqvMKU3N4HUwLDycFLgxz4vwZNDAL/Bc2EQ1NzaUaG4x3bVp3cS1CjwUlXL1K6ESZ5jzhz4Ib/uDcMxIwiwg9wic/7/QC/r97Q8X5Z+ZF4DMxDEf3g0oJXZbq9fSRyjMxiI/KZg8/cFl7/o16HuikcVlsm2Qn0t3d2iKA6sDUDxI1gHwT4HisuXfJ8cKWu1VxVJMQkE7cumcWG/LDAjxcn2z4/5kgIISyW/GuWPGux8XI89lyIcCMR0+juC1eFyYOkCO2oO3ZfG9atlebvKtq4wiW0jNbKqnjtqyYRN7ZNBNg5MN7J9uIzxIEon8PBLlLULE7VEABzFjeYGdFM7Gy/I7po4/taAW2z1+DFeydKDxKqXt8SMc6NUyEId4FcPii4XCU7QIBU5Xd6LxnPzmcQBpQajJepDmXZBepM5HVmSfxsE3l2N9PSSGPgISEEluNWurINlVhfhWMEip2xdNaVqSQMtohrolBcpDLYORHGF27vEJBdhEFNL1YtBe6n3J9mzv9YuqT15bvJdHGH1auOESGKmiPk6BJiKBq+1+edL/0RaurJk6FJq0bVV2IyBNwXPCTva+q9k6ak/+LjYciR6R7u4qJYBbfGg5mGjFXwRQQHM0DQgxo85UBv/qNu0TP0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-White-People_459
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy